---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _data/quotes.csv
  label: Quotes
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: _ragbrai
  label: Ragbrai
  create: all
  match: "**/*"
  templates:
  - ragbrai
- type: document
  path: _data/ragbrai.yaml
  label: RAGBRAI Data
- type: directory
  path: _members
  label: Members
  create: all
  match: "**/*"
  templates:
  - member
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
